# PostgreSQL. Versions 9.3 and up are supported.

default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    host: <%= ENV.fetch("HOST_PAGA3") %>
    database: <%= ENV.fetch("DATABASE_PAGA3") %>
    port: <%= ENV.fetch("PORT_PAGA3") %>
    username: <%= ENV.fetch("USERNAME_PAGA3") %>
    password: <%= ENV.fetch("PASSWORD_PAGA3") %>

test:
    <<: *default
    database: rails_paga3_test

    # Instead, provide the password as a unix environment variable when you boot
    # the app. Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
    # for a full rundown on how to provide these environment variables in a
    # production deployment.
    #
    # On Heroku and other platform providers, you may have a full connection URL
    # available as an environment variable. For example:
    #
    #   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"

production:
    <<: *default
    host: <%= ENV.fetch("HOST_PAGA3") %>
    database: <%= ENV.fetch("DATABASE_PAGA3") %>
    port: <%= ENV.fetch("PORT_PAGA3") %>
    username: <%= ENV.fetch("USERNAME_PAGA3") %>
    password: <%= ENV.fetch("PASSWORD_PAGA3") %>

